### ISSUE TITLE
Can't tap after hitting play in Quest

### ISSUE THREAD

**Issue by zjm-meta** [CadenzaVR/cadenza#20]
Hello. I just observed an issue that I can't tap any keys in the game after I hit the `play` button. I can tap correctly in the song selection page but I just can't anymore after I hit play. I can still see my hand's position updated corretly.

In the console I can see some exceptions like

index.js:31 Uncaught TypeError: Cannot read properties of undefined (reading 'gamepad')
    at t (index.js:31:24)
    at d.<anonymous> (index.js:45:9)
    at d.emit (a-node.js:293:10)
    at e.exports.checkControllerPresentAndSetup (tracked-controls.js:41:8)
    at n.checkIfControllerPresent (oculus-touch-controls.js:232:5)
    at n.checkIfControllerPresent (bind.js:12:17)
    at n.onControllersUpdate (oculus-touch-controls.js:308:10)
    at v.<anonymous> (bind.js:12:17)
    at v.emit (a-node.js:293:10)
    at i.updateControllerList (tracked-controls-webxr.js:81:13)

clickable.ts:73 Uncaught TypeError: Cannot read properties of null (reading 'el')
    at i.deactivateClickable (clickable.ts:73:41)
    at d.<anonymous> (clickable.js:28:21)
    at d.emit (a-node.js:293:10)
    at collider.onCollisionExit (collider.ts:18:21)
    at o.collisionEnd (Collider.ts:23:14)
    at d.update (CollisionDetectionSystem.ts:198:51)
    at i.tick (collision-detection.ts:51:43)
    at v.tick (a-scene.js:703:36)
    at v.render (a-scene.js:743:32)
    at bind.js:12:17

Can you try to test and see if you can repro this issue on your side? Thanks.

**Comment by devmaxxing** [comment]
Hi @zjm-meta. Yes I've replicated the issue and traced it to a bug in the production collision detection system which I have just pushed a fix for.
The gamepad error just affects the haptics component which I will fix separately.
